Repository Cylink-KSM-Cyber/frontend-cylink, pull requests merged in 2025-05, with the labels that each got.

#44 fix: clear build cache after successful workflow
  .github/workflows/deploy.prod.yml
  .github/workflows/deploy.staging.yml
Labels: enhancement

#45 fix: only clear build cache instead of entire cache
  .github/workflows/deploy.prod.yml
  .github/workflows/deploy.staging.yml
Labels: enhancement

#46 chore: revert back to system prune
  .github/workflows/deploy.prod.yml
  .github/workflows/deploy.staging.yml
Labels: enhancement

#52 v0.9.0-beta
  README.md
  package-lock.json
  public/images/model.png
  src/app/layout.tsx
  src/app/page.tsx
  src/components/atoms/DecryptedText.tsx
  src/components/atoms/FeatureIcon.tsx
  src/components/atoms/FooterColumnTitle.tsx
  src/components/atoms/FooterLink.tsx
  src/components/atoms/JapanesePattern.tsx
  src/components/atoms/KeyHighlight.tsx
  src/components/atoms/Logo.tsx
  src/components/atoms/MissionCard.tsx
  src/components/atoms/NavButton.tsx
  src/components/atoms/NavbarDecorations.tsx
  src/components/atoms/SectionTitle.tsx
  src/components/atoms/SocialIcon.tsx
  src/components/atoms/StatisticCard.tsx
  src/components/atoms/StepIndicator.tsx
  src/components/molecules/AboutContent.tsx
  src/components/molecules/FeatureCard.tsx
  src/components/molecules/FooterColumn.tsx
  src/components/molecules/FooterSocialLinks.tsx
  src/components/molecules/HeroCallToAction.tsx
  src/components/molecules/Navbar.tsx
  src/components/molecules/ProcessStep.tsx
  src/components/organisms/AboutSection.tsx
  src/components/organisms/CallToActionSection.tsx
  src/components/organisms/FeaturesSection.tsx
  src/components/organisms/FooterSection.tsx
  src/components/organisms/HeroSection.tsx
  src/components/organisms/HowItWorksSection.tsx
  src/components/organisms/KSMCyberSecuritySection.tsx
  src/components/templates/HomeTemplate.tsx
  src/hooks/useHoverEffect.ts
  src/interfaces/hero.ts
  src/interfaces/navbar.ts
  src/styles/about.css
  src/styles/callToAction.css
  src/styles/features.css
  src/styles/footer.css
  src/styles/hero.css
  src/styles/howitworks.css
  src/styles/ksm.css
Labels: bug, documentation, enhancement

#56 hotfix: url status expiration display
  src/app/dashboard/urls/page.tsx
  src/components/molecules/UrlFilter.tsx
  src/components/molecules/UrlsTable.tsx
  src/components/organisms/UrlList.tsx
  src/hooks/url/useUrlTotalClicks.ts
  src/hooks/useUrls.ts
  src/interfaces/url.ts
  src/services/url.ts
Labels: bug, enhancement

#58 feat: implement responsive forgot password page with modal success state and blur backdrop effect
  src/app/forgot-password/forgot-password.css
  src/app/forgot-password/page.tsx
  src/components/atoms/Input.tsx
  src/components/molecules/EmailSentModal.tsx
  src/components/molecules/ForgotPasswordForm.tsx
  src/components/organisms/ForgotPasswordContainer.tsx
  src/components/templates/ForgotPasswordTemplate.tsx
  src/hooks/useForgotPassword.ts
  src/interfaces/auth.ts
  src/services/auth.ts
Labels: documentation, enhancement
